### ISSUE TITLE
Module resolving failed when bumping to new version of metro-config

### ISSUE THREAD

**Issue by rurikoaraki** [microsoft/rnx-kit#1060]
### What happened?

I'm not sure if this is intended, so opening an issue as a question.

We have a PR open to bump to the latest version of the metro-config package:
https://github.com/microsoft/fluentui-react-native/pull/1327

However the bundle step was failing in our Windows PR due to modules not being resolved. If I add `resolverMainFields: ['main']` to our `makeMetroConfig`, the issue goes away, but this effectively undoes what https://github.com/microsoft/rnx-kit/pull/981 changed. Is the break we're having expected? And is our workaround the expected way for us to "fix" the problem?

Logs: https://dev.azure.com/ms/ui-fabric-react-native/_build/results?buildId=267639&view=logs&jobId=52dee7c6-1a21-55bd-a3d4-2c2cda043ccf&j=52dee7c6-1a21-55bd-a3d4-2c2cda043ccf&t=03ff1979-ccbd-582e-c969-14078c9c0286

### Affected Package

@rnx-kit/metro-config

### Version

1.2.27

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### System Information

```true
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 101.11 GB / 127.86 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    Visual Studio: 17.0.31919.166 (Visual Studio Enterprise 2022), 16.11.32002.261 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.12 - C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1. Pull https://github.com/microsoft/fluentui-react-native/pull/1327
2. Undo last commit
3. Run `yarn` from root of repo
4. Go to `apps\windows` directory and run `yarn bundle`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
I had a very quick a look at this and I think there's a config inconsistency in FURN. In general, the `module` field is supposed to point to an ESM module. I see that most packages are pointing to `src/index.ts`, which I suppose is okay, but there are three packages that are pointing to a non-existent `lib/index.js`:

```
packages/theming/theming-utils/package.json:11:  "module": "lib/index.js",
packages/utils/styling/package.json:6:  "module": "lib/index.js",
packages/utils/test-tools/package.json:6:  "module": "lib/index.js",
```

Is this intentional? Otherwise, I think changing them to `src/index.ts` like the other packages will address your build issue.

**Comment by rurikoaraki** [comment]
@tido64 Sorry for the really late reply. Thanks for looking at our files, the fix your recommended worked and I'm able to bundle just fine with this update now.
