### ISSUE TITLE
RN Dev version while running dep-check in vigilant mode without giving `reactNativeDevVersion`  in dep-check config

### ISSUE THREAD

**Issue by AlekhyaYalla** [microsoft/rnx-kit#1140]
As per the dep-check@1.12.0, the dep-check config in the package.json doesn't necessarily need `reactNativeDevVersion` in vigilant mode. When we tried in our repo, where we are running in vigilant mode, without giving `reactNativeVersion` and `reactNativeDevVersion` in dep-check config in package.json as below, 
```json
{
  "name": "my_package",
  "description": "code base",
  "version": "0.0.1",
  "main": "lib/index.js",
  "dependencies": {
  },
  "peerDependencies": {
    "react": "~16.9.0 || ~16.11.0 || ~16.13.1",
    "react-dom": "~16.9.0 || ~16.11.0 || ~16.13.1 || ~17.0.1",
    "react-native": "^0.61.5 || ^0.62.3 || ^0.63.2 || ^0.64.2"
  },
  "devDependencies": {
    "cross-os": "^1.3.0",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "^0.62.3",
    "typescript": "^4.5.2"
  },
  "rnx-kit": {
    "customProfiles": "dep-check-profiles"
  },
  "sideEffects": false
}

```
and params I pass to dep-check cli command are `dep-check 0.62`
```js
cli({
  vigilant: `[arg ],0.61,0.62,0.63`,
  [other params]
});

```
In this run, I expect the dep-check to verify my package.json against the `0.62` profile as I passed it while running the command, but it is verifying against the `0.61` profile.
below is the result of running dep-check.
```JSON
  {
    "name": "my-package",
    "description": "code base",
    // rest of package.json
    "peerDependencies": {
      "react": "~16.9.0 || ~16.11.0 || ~16.13.1",
      "react-dom": "~16.9.0 || ~16.11.0 || ~16.13.1 || ~17.0.1",
-     "react-native": "^0.61.5 || ^0.62.3 || ^0.63.2 || ^0.64.2"
+     "react-native": "^0.61.5 || ^0.62.3 || ^0.63.2"
    },
    "devDependencies": {
      "cross-os": "^1.3.0",
-     "react": "~16.11.0",
+     "react": "~16.9.0",
      "react-dom": "~16.11.0",
-     "react-native": "^0.62.3",
+     "react-native": "^0.61.5",
      "typescript": "^4.5.2"
    },
    "rnx-kit": {
      "customProfiles": "dep-check-profiles"
    }
  }
// Please make a note of +/- in the above json, as 
// + lines are suggestion to add by dep-check
// - lines are suggestion to remove by dep-check
```
 In the above, it is picking the `0.61` version of react dev version, but not the version I have given while running. 
 
 Is this the expected behavior, 
       - if yes then it should actually pick the dev version that I passed through command, isn't it?
 if it's not expected behavior, please help me with right way?

**Comment by tido64** [comment]
It's not clear to me what arguments you passed to cli. If you take a look in the `README`, it states that the first value specified is interpreted as target version:

https://github.com/microsoft/rnx-kit/blob/0a73d3472dd731b3baa7a5c23a949590773c8848/packages/dep-check/README.md?plain=1#L128-L132

In other words, specifying `0.61,0.62,0.63` is equivalent to having:

```json
{
  "rnx-kit": {
    "reactNativeVersion": "0.61,0.62,0.63",
    "reactNativeDevVersion": "0.61"
  }
}
```

**Comment by AlekhyaYalla** [comment]
Here is my cli parameters, 
```
cli({
  vigilant: `[arg],0.61,0.62,0.63`,
  [other params]
});
```
where arg I'm passing is 0.62. which resolves the parameters to
```
cli({
  vigilant: `0.62,0.61,0.62,0.63`,
  [other params]
});
```

In this case, as mentioned (and expected) the target version should be `0.62`. isn't it?

**Comment by tido64** [comment]
Can you try hard-coding the parameter to `vigilant`? I've tried it locally and can't repro the issue you're seeing.
