### ISSUE TITLE
'package.json' does not contain a valid package manifest

### ISSUE THREAD

**Issue by ogdenstudios** [microsoft/rnx-kit#1190]
### What happened?

Hey folks, I have a project which was originally built in Expo. Then we ejected to the bare workflow. 

I heard about y'all from the React Native podcast. I wanted to use this tool for an upgrade I'm working on. 

I ran the following commands: 

```
yarn add @rnx-kit/dep-check --dev 
yarn rnx-dep-check package.json 
```

The install worked, but when running the dependency check, I get this error: 

`'package.json' does not contain a valid package manifest`

Is this me? Or a bug? 

### Affected Package

@rnx-kit/dep-check

### Version

1.12.6

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 253.36 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /var/folders/cp/d4ldtj4s6vn7nw41txkf9j640000gn/T/yarn--1646447948836-0.08367085635543492/node
    Yarn: 1.22.11 - /var/folders/cp/d4ldtj4s6vn7nw41txkf9j640000gn/T/yarn--1646447948836-0.08367085635543492/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.02.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/tylerwilliams/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 7.70s.
```

### Steps to Reproduce

```
yarn add @rnx-kit/dep-check --dev 
yarn rnx-dep-check package.json 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @ogdenstudios, `rnx-dep-check ` checks that both `name` and `version` are present in the `package.json`:
https://github.com/microsoft/rnx-kit/blob/440cd77071a4e2b4dc6960dbe08bbc000f68ddd3/packages/tools-node/src/package.ts#L97-L106

Are you missing either fields?

**Comment by ogdenstudios** [comment]
Oh yup, I certainly am. Thanks so much @tido64! Really appreciate the help. Can't wait to use this tool!
