### ISSUE TITLE
Change repo name?

### ISSUE THREAD

**Issue by afoxman** [microsoft/rnx-kit#1251]
Revisit name "rnx-kit" and collectively accept or replace it. Update packages and documentation. npm deprecate.

**Comment by kelset** [comment]
my 2C$ at this point in time (not a strong opinion, might change in the future):
* rnx-kit as a repo name / npm org name is fine: it's short and has something "catchy" about it
* on the other hand, it really doesn't communicate anything about what it is (2 TLA back to back)
* I think that the most effective option would be to just create a good tagline for it, along the lines of "rnx-kit, the developer toolbox for the react-native developer" or something like that. Like, we need to have a one-liner that describes it

**Comment by afoxman** [comment]
We'll keep the name, and use it as a moniker, with our main name and tagline being React Native Developer Tools -- Modern, scalable tools. Exceptional developer experience.
