### ISSUE TITLE
how-to guide for using react-native and TypeScript together

### ISSUE THREAD

**Issue by afoxman** [microsoft/rnx-kit#1276]
Write a how-to guide for configuring TypeScript for react-native projects whose types vary by platform and need per-platform validation.

**Comment by kelset** [comment]
quick note here, we should probably collaborate with the maintainers of https://github.com/react-native-community/react-native-template-typescript - they are on the Discord so it should be easy to coordinate and make sure it's all aligned, after all this template is how most folks get started with TS (https://reactnative.dev/docs/typescript)

**Comment by kelset** [comment]
also related: https://github.com/reactwg/react-native-new-architecture/discussions/22

(this is specifically about the new architecture support)

**Comment by kelset** [comment]
closing this since 0.71 onward TS is default https://reactnative.dev/blog/2023/01/12/version-071
