### ISSUE TITLE
Poll the react-native community regarding bundle splitting via Metro

### ISSUE THREAD

**Issue by afoxman** [microsoft/rnx-kit#1282]
Ask the react-native community (Twitter, Discord) about bundle-splitting using Metro. 

Is anyone doing it? 
If not, and we built it, would they use it? 
How does it fit into a Hermes world with byte-code bundles that favor a single mult-app bundle. 

For those interested in module federation, how is this different? Should module federation be pursued concurrently as part of the same workstream?

Use the results to inform bundle-splitting scenario development, and to set the priority of this work.

Note the most enthusiastic respondents, and consider partnering with them as contributors and/or early adopters.

**Comment by ecreeth** [comment]
I think [callstack/react-native-multibundle](https://github.com/callstack/react-native-multibundle) may be useful.
