### ISSUE TITLE
Metro: Also enable `disableImportExportTransform` when `experimentalImportSupport` is

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#142]
When enabling `experimentalImportSupport` in `metro.config.js`:

```js
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: true,
        inlineRequires: true,
      },
    }),
  },
};
```

`disableImportExportTransform` should also be enabled in `babel.config.js`:

```js
module.exports = {
  presets: [
    [
      "module:metro-react-native-babel-preset",
      { disableImportExportTransform: true },
    ],
  ],
};
```

When `babel.config.js` is missing, `disableImportExportTransform` is set to the value of `experimentalImportSupport` in [`metro-react-native-babel-transformer`](https://github.com/facebook/metro/blob/fa096594bcdeda8fe529aba94604016a1c3cbf93/packages/metro-react-native-babel-transformer/src/index.js#L93). Since we're recommending folks to use our preset, we need to find a way to keep both in sync somehow.

**Comment by denissb** [comment]
Spent quite some time figuring this out today. I think enabling `experimentalImportSupport` needs to be explicitly mentioned in the docs herehttps://microsoft.github.io/rnx-kit/docs/guides/bundling#tree-shaking.
