### ISSUE TITLE
Feature request: DepCheck: Detect and 'fix' missing peer dependencies

### ISSUE THREAD

**Issue by dannyvv** [microsoft/rnx-kit#1454]
I'm trying to fix hidden cyclic dependencies hidden by yarn v1 in one of our internal repo's by using midgard-yarn-strict.
Here I'm running into many peer dependencies not being properly declared in the react-native pacakges (both core, from microsoft and from community). With babel being a common missing ones.

I can point you to some files where other internal repo's already on midgard-yarn-strict that have extra dependency declarations.

**Comment by dannyvv** [comment]
@[tido64](https://github.com/tido64) as FYI:

**Comment by afoxman** [comment]
Hi @dannyvv, can you explain what you mean by "fix"? An example or two would help a lot.
