### ISSUE TITLE
Metro: 'd' (debug) command not working with newer CLI builds

### ISSUE THREAD

**Issue by afoxman** [microsoft/rnx-kit#1485]
### What happened?

In PR #1484, @tido64 found that the 'd' (debug) command no longer works from the interactive Metro terminal when running a bundle server.

### Affected Package

@rnx-kit/cli

### Version

0.12.3

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [X] macOS
- [X] Windows

### System Information

```true
n/a
```

### Steps to Reproduce

yarn run react-native rnx-start

Start a native app an attach to the bundle server.

Then press 'd' once the server is up. A debug menu should appear in the native app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Plot-twist:

- The `devMenu` command was only ever implemented on Android: https://github.com/facebook/react-native/commit/01adc71ade1c3453705e5c744fa836aa2ca23e3c
- It was added to `@react-native-community/cli` in 3.0.5-alpha.1: https://github.com/react-native-community/cli/commit/25a2c44c4a52341110e7a64d681aaefaf4726a97
- It's been over three years and apparently no-one has noticed?

@kelset: Is this something worth filing an issue upstream?

**Comment by kelset** [comment]
yeah, I'd close this and upstream/mention this problem here: https://github.com/react-native-community/cli/issues/1820 so that the CLI team can look into that

**Comment by tido64** [comment]
Reported upstream. Closing this issue.
