### ISSUE TITLE
Module not found @rnx-kit/metro-resolver-symlinks RN0.63.4

### ISSUE THREAD

**Issue by FrederickEngelhardt** [microsoft/rnx-kit#1567]
### What happened?

# Issue
Unable to resolve the module xyz from "symlinked-repo"

This happens after running a yarn link to a package located within the monorepo react-native app. Cache has been reset.

## Previous solution:
copy the third-party-modules output lib folder to a local module-name folder and then override the package name path in extraNodeModules.

Also see that the @rnx-kit/metro-resolver-symlinks pulls in metro-resolver 0.66 but we have a resolution forcing 0.59 due to issues with metro-bundler compatibility past 0.59 on RN 0.63.4

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.19

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 169.57 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/Library/Caches/fnm_multishells/18455_1653528545827/bin/node
    Yarn: 1.22.5 - ~/Library/Caches/fnm_multishells/18455_1653528545827/bin/yarn
    npm: 8.5.0 - ~/Library/Caches/fnm_multishells/18455_1653528545827/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 32.0.0, 32.1.0, 33.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: ^4.10.0 => 4.14.0
    react: ~16.14.0 => 16.14.0
    react-native: ~0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1. Use react-native 0.63.4
2. Have a lerna /yarn workspaces monorepo
3. Have a react native app inside one of the monorepo packages
4. Link to a package outside of the monorepo.
5. Start the server `react-native start`
6. Connect the server to iOS or Android (probably any platform)
7. Noting an error with resolving the linked package.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @FrederickEngelhardt, thanks for filing an issue. Can you post the contents of your `metro.config.js`? Does your `watchFolders` include the path to the module that you're linking to? Metro will silently ignore any resolved paths that are not under project root or paths listed in `watchFolders`.
