### ISSUE TITLE
SDK: React Native upgrade assistant

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#159]
Implement a tool for helping with RN upgrades, e.g. migrating a package on 0.62 to 0.63. It should be able to bump dependencies, remove packages that are deprecated, and make any necessary reconfigurations.

This tool should make use of the ones created in #139, #157, and #160.

**Comment by afoxman** [comment]
This should be part of our CLI.

**Comment by afoxman** [comment]
@tido64 Is this still needed? I think dep-check's `set-version` command will move the react-native version and update all dependencies.

**Comment by tido64** [comment]
Closing this. `set-version` currently does not remove packages that are deprecated. I've filed a more scoped issue here: #1299
