### ISSUE TITLE
metro-serializer-esbuild: target ES6 with individual features disabled

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#1670]
As of esbuild [v0.14.46](https://github.com/evanw/esbuild/releases/tag/v0.14.46), we can target ES6 and disable individual JS features that Hermes do not support.

**Comment by ecreeth** [comment]
Great news @tido64! the esbuild [v0.14.48](https://github.com/evanw/esbuild/releases/tag/v0.14.48) now includes [Hermes](https://hermesengine.dev/) as a JavaScript engine target. With features that are supported.

**Comment by tido64** [comment]
> Great news @tido64! the esbuild [v0.14.48](https://github.com/evanw/esbuild/releases/tag/v0.14.48) now includes [Hermes](https://hermesengine.dev/) as a JavaScript engine target. With features that are supported.

This is great news indeed! Thanks for letting me know. Going to whip up a PR to enable this.
