### ISSUE TITLE
Running rnx-bundle fails after updating to latest rnx-kit/dep-check and rnx-kit/metro-config

### ISSUE THREAD

**Issue by rurikoaraki** [microsoft/rnx-kit#1731]
### What happened?

If I revert the latest bumps to both packages, the command runs as expected.
Running react-native rnx-bundle gives the following errors:

yarn bundle
yarn run v1.22.19
warning package.json: No license field
$ react-native rnx-bundle --dev false
warn Package @rnx-kit/cli has been ignored because it contains invalid configuration. Reason: Cannot find module 'node:path'
Require stack:
- E:\fluentui-react-native\node_modules\@rnx-kit\dep-check\lib\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\lib\dep-check.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\lib\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\react-native.config.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\import-fresh\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\loaders.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\createExplorer.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\tools\config\readConfigFromDisk.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\tools\config\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\commands\install\install.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\commands\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\index.js
- E:\fluentui-react-native\node_modules\react-native\cli.js
error Unrecognized command "rnx-bundle". Did you mean "ram-bundle"?
info Run "react-native --help" to see a list of all available commands.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

yarn bundle
yarn run v1.22.19
warning package.json: No license field
$ react-native rnx-bundle --dev false
error Cannot find module 'node:path'
Require stack:
- E:\fluentui-react-native\node_modules\@rnx-kit\tools-workspaces\lib\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\metro-config\src\index.js
- E:\fluentui-react-native\apps\win32\metro.config.js
- E:\fluentui-react-native\node_modules\metro-config\node_modules\import-fresh\index.js
- E:\fluentui-react-native\node_modules\metro-config\node_modules\cosmiconfig\dist\loaders.js
- E:\fluentui-react-native\node_modules\metro-config\node_modules\cosmiconfig\dist\createExplorer.js
- E:\fluentui-react-native\node_modules\metro-config\node_modules\cosmiconfig\dist\index.js
- E:\fluentui-react-native\node_modules\metro-config\src\loadConfig.js
- E:\fluentui-react-native\node_modules\metro-config\src\index.js
- E:\fluentui-react-native\node_modules\metro\src\commands\build.js
- E:\fluentui-react-native\node_modules\metro\src\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\metro-service\lib\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\lib\bundle.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\lib\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\react-native.config.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\import-fresh\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\loaders.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\createExplorer.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\tools\config\readConfigFromDisk.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\tools\config\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\commands\install\install.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\commands\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\index.js
- E:\fluentui-react-native\node_modules\react-native\cli.js.
Error: Cannot find module 'node:path'
Require stack:
- E:\fluentui-react-native\node_modules\@rnx-kit\tools-workspaces\lib\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\metro-config\src\index.js
- E:\fluentui-react-native\apps\win32\metro.config.js
- E:\fluentui-react-native\node_modules\metro-config\node_modules\import-fresh\index.js
- E:\fluentui-react-native\node_modules\metro-config\node_modules\cosmiconfig\dist\loaders.js
- E:\fluentui-react-native\node_modules\metro-config\node_modules\cosmiconfig\dist\createExplorer.js
- E:\fluentui-react-native\node_modules\metro-config\node_modules\cosmiconfig\dist\index.js
- E:\fluentui-react-native\node_modules\metro-config\src\loadConfig.js
- E:\fluentui-react-native\node_modules\metro-config\src\index.js
- E:\fluentui-react-native\node_modules\metro\src\commands\build.js
- E:\fluentui-react-native\node_modules\metro\src\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\metro-service\lib\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\lib\bundle.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\lib\index.js
- E:\fluentui-react-native\node_modules\@rnx-kit\cli\react-native.config.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\import-fresh\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\loaders.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\createExplorer.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\node_modules\cosmiconfig\dist\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\tools\config\readConfigFromDisk.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\tools\config\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\commands\install\install.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\commands\index.js
- E:\fluentui-react-native\node_modules\@react-native-community\cli\build\index.js
- E:\fluentui-react-native\node_modules\react-native\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (E:\fluentui-react-native\node_modules\@rnx-kit\tools-workspaces\lib\index.js:36:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Seems like the new workspace-tools package that was added (https://github.com/microsoft/rnx-kit/commit/37245c33c63f3e676121167ab248b72522cdc88e) imports from the referenced node:path package and it's failing to find it on our machines? Interestingly our CI machine runs fine.

My installed Node version is v14.17.1 which I think is within the declared support range. But I read somewhere that node:path may only be supported on >= v16?

### Affected Package

@rnx-kit/dep-check and @rnx-kit/metro-config

### Version

1.12.18 and 1.2.34, respectively

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### System Information

```true
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 111.58 GB / 127.86 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    Visual Studio: 17.2.32602.215 (Visual Studio Enterprise 2022), 16.11.32602.291 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.12 - C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1. Pull latest https://github.com/microsoft/fluentui-react-native
2. yarn
3. yarn build
4. cd apps\win32
5. yarn bundle

May need to change node to v 14.17.1 or similar version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
This is… surprising. Our CIs run both 14 and 16, so this should've been caught. I see in the logs that they are running [14.19.3](https://github.com/microsoft/rnx-kit/pull/1717/checks#step:3:19). Did you try upgrading to latest 14.x?

**Comment by tido64** [comment]
Looks like support for the `node:` prefix was added in [14.18](https://nodejs.org/en/blog/release/v14.18.0/). It's already late where I am so I will update the requirements next week unless someone has already taken care of it.

**Comment by rurikoaraki** [comment]
> Looks like support for the `node:` prefix was added in [14.18](https://nodejs.org/en/blog/release/v14.18.0/). It's already late where I am so I will update the requirements next week unless someone has already taken care of it.

Got it, thanks for the clarification. I'll tell my team to update their node versions. Updating to 14.20 worked for me.

Thanks for looking into this so quickly!
