### ISSUE TITLE
Getting error on tests when using @rnx-kit/babel-preset-metro-react-native 

### ISSUE THREAD

**Issue by JerryMacedoCastro** [microsoft/rnx-kit#1737]
### What happened?

My react-native app asks for a babel plugin  when I run the unit tests. I guess one goal of rnx-kit is no need several things installed in order to your app works. 

Here is the error message: 
![image](https://user-images.githubusercontent.com/39466788/178336934-d32a14a2-6658-46e4-9e4a-4974702985c1.png)

### Affected Package

@rnx-kit/babel-preset-metro-react-native

### Version

^1.1.0

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### System Information

```true
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 6.70 GB / 16.00 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32510.428 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1 - install "@rnx-kit/babel-preset-metro-react-native": "^1.1.0",

2- remove babel plugins
    "@babel/plugin-transform-flow-strip-types": "^7.1.6",
    "@babel/plugin-transform-object-assign": "^7.1.6",
    "@babel/plugin-transform-react-jsx-source": "^7.16.7"

3- run tests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afoxman** [comment]
Hi @JerryMacedoCastro, can you share a link to your project so I can reproduce the issue and see what is going on?

**Comment by JerryMacedoCastro** [comment]
I created the repo with the same configuration but the erros doesn't occurs. Here is the link https://github.com/JerryMacedoCastro/rnxkitexample

I'm working with yarn workspaces I don't if this can be related.

**Comment by afoxman** [comment]
Hmmm... Without a reproduction of the error, there's not much I can do to help. Sorry.
