### ISSUE TITLE
Support for the "link" protocol

### ISSUE THREAD

**Issue by SchlagerKhan** [microsoft/rnx-kit#1762]
### What happened?

Using `yarn@3.2.1` with the following `package.json`:

```json
{
  ...
  "dependencies": {
    "app": "link:src",
  }
}
```

and running `yarn rnx-deps-check` gives the following error:

```
error package.json: ENOENT: no such file or directory, open '/.../app/src/package.json'
```

### Affected Package

@rnx-kit/dep-check

### Version

1.12.18

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 36.46 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /private/var/folders/xt/bb9ddqg51_jfz2rmh0cvzvzm0000gn/T/xfs-4bf73da4/node
    Yarn: 3.2.1 - /private/var/folders/xt/bb9ddqg51_jfz2rmh0cvzvzm0000gn/T/xfs-4bf73da4/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

In any project that uses `yarn@2+`, add any local dependency with the `link` protocol and run the deps command.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @SchlagerKhan, I am unable to reproduce your issue. This is what I did in a separate repo of mine:

- Add `"@react-native-async-storage/async-storage": "link:../../async-storage"`
- Run `yarn`
- Run `yarn rnx-dep-check`

It's only when I add `/src` to the path above that I got the error you hit. Do you have a minimal repro of this somewhere so I can see the issue for myself? Frankly, it doesn't seem like a bug with dep-check from first impression.
