### ISSUE TITLE
Cannot resolve react-native in symlinked package with peerDependencies

### ISSUE THREAD

**Issue by scottmas** [microsoft/rnx-kit#1804]
### What happened?

A symlinked package depended on by my react-native app cannot find it's peer dependency react-native. The error is as follows

```
 Error: Unable to resolve module react-native from /Users/scottashton/projects/umbrella-corp/shared/rn-typed-router/dist/implementations/primitives.native.js:
None of these files exist:
 ../../../node_modules/.pnpm/react-native@0.69.1_react@18.2.0/node_modules/react-native(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
../../../node_modules/.pnpm/react-native@0.69.1_react@18.2.0/node_modules/react-native/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
```

The issue is fixed when I add a custom remapModule to MetroSymlinksResolver like so:
```
MetroSymlinksResolver({
  remapModule: (context, moduleName, platform) => { 
    if (moduleName.match(/^(react-native)$/)) {
      return require.resolve(moduleName);
    }
    return moduleName;
},
```

It seems like the fix should be to resolve the nearest `package.json` from `originModulePath` and see if the requested `moduleName` is in `peerDependencies`. If it is, resolve `moduleName` from root of the react-native app, otherwise resolve as per normal.

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.21

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
Using PNPM as package manager.

System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 105.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Use PNPM as package manager. Then have a dependency tree as follows:

```
some-rn-app:
  -dependencies:
    -some-workspace-dependency
    -react-native

some-workspace-dependency
  -peerDependencies
    -react-native
```

When react-native is imported inside of some-workspace-depency the error will occur. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afoxman** [comment]
Hi @scottmas,

Thanks for bringing this problem to our attention! I tried to create a reproduction, with an app package that depends on a lib package, and the lib relies on its peerDependency of react-native. 

Everything seems to be working fine.

The repo I made is here: https://github.com/afoxman/rnx-kit-repro-1804

Can you submit a PR to it which creates the failing condition you are seeing, or create your own minimal reproduction and share a link to it?

**Comment by scottmas** [comment]
The issue seems to magically have gone away. It may have been something weird I was doing, I don't fully know. If anything like it happens again I'll do a rock solid repro before posting again. Thank you so much once again for what you're doing here. You're basically the only hope these days for devs trying to get RN working on monorepos!

**Comment by afoxman** [comment]
Hi @scottmas, glad to hear things are working for you, and that the tools are helping you! Repros are appreciated - I normally ask, but had some time so decided to dive in here.
