### ISSUE TITLE
Cannot find module 'metro'

### ISSUE THREAD

**Issue by Jokerwolf** [microsoft/rnx-kit#1835]
### What happened?

Hey everyone! RNXKit was working perfectly fine and just gave up one day. Can't really understand why.
Here is the output if it helps:

`repos/monorepo_study [study] > yarn ios:start
yarn run v1.22.15
$ yarn workspace @mymonorepo/mobile ios
$ react-native run-ios
error Failed to load configuration of your project.
Error: Cannot find module 'metro'
Require stack:
- <path_to_repo>/node_modules/@rnx-kit/metro-service/lib/index.js
- <path_to_repo>/node_modules/@rnx-kit/cli/lib/bundle.js
- <path_to_repo>/node_modules/@rnx-kit/cli/lib/index.js
- <path_to_repo>/node_modules/@rnx-kit/cli/react-native.config.js
- <path_to_repo>/apps/mobile/node_modules/import-fresh/index.js
- <path_to_repo>/apps/mobile/node_modules/cosmiconfig/dist/loaders.js
- <path_to_repo>/apps/mobile/node_modules/cosmiconfig/dist/createExplorer.js
- <path_to_repo>/apps/mobile/node_modules/cosmiconfig/dist/index.js
- <path_to_repo>/apps/mobile/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js
- <path_to_repo>/apps/mobile/node_modules/@react-native-community/cli-config/build/loadConfig.js
- <path_to_repo>/apps/mobile/node_modules/@react-native-community/cli-config/build/index.js
- <path_to_repo>/apps/mobile/node_modules/@react-native-community/cli/build/commands/index.js
- <path_to_repo>/apps/mobile/node_modules/@react-native-community/cli/build/index.js
- <path_to_repo>/apps/mobile/node_modules/react-native/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (<path_to_repo>/node_modules/@rnx-kit/metro-service/lib/index.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: ~/.nvm/versions/node/v16.15.0/bin/node
Arguments: ~/.node/corepack/yarn/1.22.15/lib/cli.js ios
Directory: <path_to_repo>/apps/mobile
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

### Affected Package

@rnx-kit/cli

### Version

0.14.2

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 28.35 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - ~/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Start iOS app with a yarn command.
Observe the error above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jokerwolf** [comment]
adding **/@rnx-kit/** to _nohiost_ seems to solve the issue.

**Comment by afoxman** [comment]
Hi @jokerwolf, sounds like something in your repo (somewhere) changed causing the dependencies to be updated. If that's right, it makes sense that isolating the dependency (not hoisting it to the root) helped fix the issue.

**Comment by Jokerwolf** [comment]
Hey @afoxman, after further discussion, the _nohoist_'ing of the @rnx-kit is the correct approach, so this issue can be closed - all good )
