### ISSUE TITLE
Pass more than one package.json path to dep-check

### ISSUE THREAD

**Issue by AlekhyaYalla** [microsoft/rnx-kit#1862]
Currently, dep-check allows a path to package.json through optional parameters, else it will look for node module resolution for package.json(s).

Can we have a feature like passing more than a single package, either via a list of paths or taking the glob patterns?
Eg: `yarn rnx-dep-check packages/*` | `yarn rnx-dep-check pkg-a, pkg-b,pkg-c`

Is this something feasible or intentionally ignored for any specific reason? 

Thank you!

**Comment by tido64** [comment]
This is something we should be able to support.
