### ISSUE TITLE
RFC 0001: dep-check v2

### ISSUE THREAD

**Issue by afoxman** [microsoft/rnx-kit#1890]
This issue tracks commits associated with [RFC 0001: dep-check v2](https://github.com/microsoft/rnx-kit/pull/1757).

Please reference it when making PRs against the repo.

- Migration:
  - [x] https://github.com/microsoft/rnx-kit/pull/1927
  - [x] https://github.com/microsoft/rnx-kit/pull/1931
  - [x] https://github.com/microsoft/rnx-kit/pull/1937
  - [x] https://github.com/microsoft/rnx-kit/pull/1940
  - [x] https://github.com/microsoft/rnx-kit/pull/1911
  - [x] https://github.com/microsoft/rnx-kit/pull/1930
  - [x] https://github.com/microsoft/rnx-kit/pull/1938
  - [x] https://github.com/microsoft/rnx-kit/pull/1948
  - [x] https://github.com/microsoft/rnx-kit/pull/1949
  - [x] https://github.com/microsoft/rnx-kit/pull/1950
  - [x] https://github.com/microsoft/rnx-kit/pull/1951
  - [x] https://github.com/microsoft/rnx-kit/pull/1953
  - [x] https://github.com/microsoft/rnx-kit/pull/1958
  - [x] https://github.com/microsoft/rnx-kit/pull/1972
  - [x] https://github.com/microsoft/rnx-kit/pull/1973
  - [x] https://github.com/microsoft/rnx-kit/pull/1975
  - [x] https://github.com/microsoft/rnx-kit/pull/1959
  - [x] https://github.com/microsoft/rnx-kit/pull/1960
  - [x] https://github.com/microsoft/rnx-kit/pull/1977
  - [x] https://github.com/microsoft/rnx-kit/pull/1979
  - [x] https://github.com/microsoft/rnx-kit/pull/1980
  - [x] https://github.com/microsoft/rnx-kit/pull/2023
- Release:
  - [x] https://github.com/microsoft/rnx-kit/pull/1981
  - [x] https://github.com/microsoft/rnx-kit/pull/1978
- Post-release:
  - [ ] https://github.com/microsoft/rnx-kit/pull/1976
  - [x] https://github.com/microsoft/rnx-kit/pull/1941

**Comment by tido64** [comment]
I've created https://github.com/microsoft/rnx-kit/issues/2031 to handle post-release tasks. Closing this issue as completed. Thanks again, everyone!
