### ISSUE TITLE
dep-check: Show warning for react-native 0.70x when @types/react-native was found as dependency

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#1899]
### Discussed in https://github.com/microsoft/rnx-kit/discussions/1898

<div type='discussions-op-text'>

<sup>Originally posted by **davydspotnana** September 22, 2022</sup>
`@types/react-native` was merged into react-native repo 

> The current plan is to release `@types/react-native` for `0.70` and `0.71` while also maintaining types here. This will result in some double maintenance until `0.72` but will give community time to move off of `@types/react-native`.

See: https://github.com/facebook/react-native/pull/34614

So it's not need any more to install `@types/react-native` for new versions on react native </div>

**Comment by retyui** [comment]
First version RN with built-in types will be `0.71.x`

> These changes will be in the 0.71 release so you can remove the @types/react-native requirement for anyone using 0.71

https://github.com/react-native-community/discussions-and-proposals/discussions/490#discussioncomment-3693520
