### ISSUE TITLE
Resolver does not support `@/` paths

### ISSUE THREAD

**Issue by matthew-dean** [microsoft/rnx-kit#1923]
### What happened?

It's common in projects to have settings like this (from tsconfig.json):
```json
"baseUrl": ".",
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
```
In other words, using `@/` as a "source-relative" reference. This works in TypeScript, ESLint, Babel, swc, Rollup, etc, as long as all are configured correctly.

However, `@rnx-kit/tools-node` _explicitly_ forbids this, with [these lines](https://github.com/microsoft/rnx-kit/blob/main/packages/tools-node/src/package.ts#L29-L31) in package.ts. Meaning that the symlink resolver can't resolve modules the way any other module resolver would.

Therefore, this throws an error:
```ts
import { useGlobalState } from '@/context/globalContext'
```

### Affected Package

@rnx-kit/tools-node

### Version

latest

### Which platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 909.99 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/local/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Try writing this:
```ts
import { foo } from '@/bar'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afoxman** [comment]
Hi @matthew-dean, thanks for reporting this! We don't have support for the extended module resolution semantics in tsconfig. The parsing code you pointed out is looking for a package-scope, and is blissfully unaware that it might be looking at an alias of some kind.

Are you hoping to see that support added? Or do you have something more tactical in mind?
