### ISSUE TITLE
dep-check: Support to configure the capabilities change in peerDependencies section

### ISSUE THREAD

**Issue by AlekhyaYalla** [microsoft/rnx-kit#1929]
Currently, if a package.json's `rnx-kit` cofig is given with `capabilities` list, then those capabilities/dependencies will be reflected in `dependencies` section if the package is an app or in `devDependencies` & `peerDependencies` for lib type packages and no package type is provided. 
IMO, this is valid in react-native and related dependencies. In case if a dev wants to use this functionality with non react-native dependencies, which dont want to be in `peerDependencies` section, it would be better if we give that option to dev to config in `rnx-kit` config to have the capabilities reflected in `peer` section. 
Please correct me if this is not valid or if I'm missing anything.

Thank you!

**Comment by tido64** [comment]
I don't think I fully understand the scenario you're trying to address here, maybe an example or two would help.

Regardless, I disagree that this is a React Native only issue. I would suggest that you go read the original RFC to understand why `peerDependencies` is needed: https://microsoft.github.io/rnx-kit/docs/architecture/dependency-management

While it's not the ideal solution, it's what we currently have in the npm space until something better comes along. If you don't want a dependency to be managed by `dep-check`, just don't list it under capabilities. I'm going to close this as invalid. If you have any objections, feel free to leave a comment and I'll reopen it.

**Comment by AlekhyaYalla** [comment]
> While it's not the ideal solution, it's what we currently have in the npm space until something better comes along. 

I agree with this. In case, the user wants a dependency to be only in `devDependencies` section, we can achieve it using `devOnly` key in the capability definition.  But we might have use cases to have certain dependencies in only `dependencies` section like  `graphQl` or `tslib`, irrespective of package type.  Can we have the flexibility to opt in/opt out to add the capabilities into a section like keys `devOnly` ? 
I also agree with you, If `devOnly` is false or not added, adding to `devDependencies` + `peerDependencies` is the way until a better one comes along, as you said. 
I know this is a feature meant for react-native apps or libs for the right way of bundling. But I'm trying to get the flexibility to non-react-native dependencies as well. 

Eg:
Default behavior:
//let's say tslib - capability
```
{
  typescript: {
     name: "tslib",
     version: "^4.3.4"
}
```
Today dep-check works this way if I have added a capability called `tslib` to be handled.
```
 {
   "name": "experience-A",
   "version": "1.0.0",
   "devDependencies": {
+     "tslib": "^4.3.4"
   },
   "peerDependencies": {
     "react-native": "^0.63",
     "react-native-netinfo": "^5.7.1",
+    "tslib": "^4.3.4"
   },
   "rnx-kit": {
     "reactNativeVersion": "^0.63",
     "capabilities": ["core-android", "core-ios", "tslib"]
   }
 }
```
With `devOnly` set to true:
//let's say tslib is a capability
```
{
  typescript: {
     name: "tslib",
     version: "4.3.4",
     devOnly: true
}
```
Today dep-check works this way if I have added a capability called `tslib` to be handled.
```
 {
   "name": "experience-A",
   "version": "1.0.0",
   "devDependencies": {
+     "tslib": "^4.3.4"
   },
   "peerDependencies": {
     "react-native": "^0.63",
     "react-native-netinfo": "^5.7.1",
   },
   "rnx-kit": {
     "reactNativeVersion": "^0.63",
     "capabilities": ["core-android", "core-ios", "tslib"]
   }
 }
```

Ask is for below:
//let's say tslib is a capability
```
{
  typescript: {
     name: "tslib",
     version: "4.3.4",
     dependenciesOnly: true // similar devOnly opting key 
}
```
Today dep-check works this way if I have added a capability called `tslib` to be handled.
```
 {
   "name": "experience-A",
   "version": "1.0.0",
   "dependencies": {
+     "tslib": "^4.3.4"
   },
   "peerDependencies": {
     "react-native": "^0.63",
     "react-native-netinfo": "^5.7.1",
   },
   "rnx-kit": {
     "reactNativeVersion": "^0.63",
     "capabilities": ["core-android", "core-ios", "tslib"]
   }
 }
```

**Comment by tido64** [comment]
> I know this is a feature meant for react-native apps or libs for the right way of bundling. But I'm trying to get the flexibility to non-react-native dependencies as well.

This is a wrong statement to make, and I wouldn't go around spreading it to people. The examples you've brought up are problematic: You cannot have multiple copies of `graphql` or `tslib`. By putting them under `dependencies`, you are essentially forcing consumers of the package to install a second copy of it and risk bundling both. This is what we're trying to prevent with dep-check. This is why we recommend using `peerDependencies` if the package is a library. It has nothing to do with react-native.
