### ISSUE TITLE
Aliases do not support index file import

### ISSUE THREAD

**Issue by matthieuMay** [microsoft/rnx-kit#1946]
Hi using version 1.3.0, I faces a problem in the bundler trying to use aliases.

 If I have an alias defined as 
     `` "@analytics": ["app/src/analytics"],``
And I try to access the "app/src/analytics/index.ts" file than I use 
``import "@analytics"`` which fails.

I solved the problem hacking into tools-node:

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@rnx-kit/tools-node/lib/package.js b/node_modules/@rnx-kit/tools-node/lib/package.js
index b3229d4..a9254c9 100644
--- a/node_modules/@rnx-kit/tools-node/lib/package.js
+++ b/node_modules/@rnx-kit/tools-node/lib/package.js
@@ -46,12 +46,12 @@ function parsePackageRef(r) {
         // The separator must start from position >= 2 to ensure that it is '@'
         // and at least one other character. Further, the separator must have
         // at least 1 character following it, before the end of the string.
-        if (indexSeparator < 2 || indexSeparator + 2 >= r.length) {
+        if (indexSeparator >= 0 && indexSeparator < 2 || indexSeparator + 2 >= r.length) {
             throw new Error(`Invalid package reference: "${r}"`);
         }
         return {
             scope: r.substring(0, indexSeparator),
-            name: r.substring(indexSeparator + 1),
+            name: indexSeparator >= 0 ? r.substring(indexSeparator + 1) : 'index',
         };
     }
     if (!r) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by tido64** [comment]
Thanks for reporting this, @matthieuMay. I've submitted a PR. Could you take a look and verify that it works in your project?

**Comment by matthieuMay** [comment]
> Thanks for reporting this, @matthieuMay. I've submitted a PR. Could you take a look and verify that it works in your project?

Thanks to you
It works great in my project
