### ISSUE TITLE
Command failed with EACCES: rnx-dep-check --init app when running in a monorepo

### ISSUE THREAD

**Issue by mikefisher84** [microsoft/rnx-kit#1954]
### What happened?

I'm trying to configure a monorepo with an expo react-native app in it managed by pnpm. 

My folder structure is like this. 

root:
---apps/mobile (contains expo app)
---apps/nextjs
---packages/ui (contains react native components)

I cd'd into the mobile folder and ran `pnpm add -D @rnx-kit/dep-check` with no problems
Then I ran `pnpm rnx-dep-check --init app` and immediately got the error 

```
 WARN  Load npm builtin configs failed, you can use "pnpm config ls" to show builtin configs. And then use "pnpm config --global set <key> <value>" to migrate configs from builtin to global.
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with EACCES: rnx-dep-check --init app
spawn rnx-dep-check EACCES
```

I also tried installing the package at the root of my monorepo workspace and got the same error. Not sure how to proceed here. 

### Affected Package

rnx-dep-check

### Version

latest

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
not relevant
```

### Steps to Reproduce

See above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @mikefisher84, could you check if `rnx-dep-check` has the executable bit set? I don't know how your project structure looks like, but you should be able to find it under some `node_modules/@rnx-kit/dep-check/lib/index.js`. If you run `ls -a <file>`, you should get something like:

```
-rwxr-xr-x  1 ... node_modules/@rnx-kit/dep-check/lib/index.js
```

The x's indicate that it's executable by owner, group, and users.
