### ISSUE TITLE
--vigilant reports errors but exits with exit code 0

### ISSUE THREAD

**Issue by Dirklectisch** [microsoft/rnx-kit#1983]
### What happened?

According to the documentation errors in the dependency tree detected while using the `--vigilant` flag should result in a non-zero exit code of the command.

https://microsoft.github.io/rnx-kit/docs/guides/dependency-management

However the command is currently exiting with code zero even if errors are reported. 

For example if I run:

`npx rnx-dep-check --vigilant 0.68`

This will report two errors in our project with the following message.

`error Changes are needed to satisfy all requirements. Re-run with --write to have dep-check apply them.`

Checking the error code from zsh reports code zero.

```
% echo $? 
0
```

This makes its impossible to have the CI fail when errors are found.

### Affected Package

@rnx-kit/dep-check

### Version

1.13.3

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.85 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: Not Found
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-31 | ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.3 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.3 => 0.68.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

- Introduce incompatible versions in `package.json` file of a project that uses `deps-check`.
- Run the checker using the `--vigilant` flag (example: `npx rnx-dep-check --vigilant 0.68`)
- Observe errors
- Observe incorrect exit code `echo #?`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @Dirklectisch,

This is really interesting. I can't repro it locally:

```
% npx rnx-dep-check --vigilant 0.68
error Found 1 violation(s) in @rnx-kit/test-app:
    react-native-webview "^1.3.5" -> "^11.22.6" (devDependencies)

% echo $?
1
```

I wonder if upgrading Node to 16.17 will help in your case. That's what I'm using here.

**Comment by Dirklectisch** [comment]
@tido64 Looks like you output is completely different from mine as well, the wording in the error message is different and my report is simple a diff instead of the succinct description you got. Mine says:

```
error Changes are needed to satisfy all requirements. Re-run with `--write` to have dep-check apply them.
info Visit https://aka.ms/dep-check for more information about dep-check.
```

(with a diff of the package file above that)

Upgrading to node `16.17.1` or `18.12.0` doesn't seem to make a difference. 

Feels like you might be testing on another version - I'm on version `1.13.3`?

```
% npm list @rnx-kit/dep-check       
iagloyaltymobile@0.0.1 /Users/dirklectisch/Projects/IAGLoyaltyMobile
└── @rnx-kit/dep-check@1.13.3
```

**Comment by tido64** [comment]
Ah, sorry… I misunderstood the first step, "introduce incompatible versions", and added an unmanaged dependency (hence the different output). This is indeed bug! I will take a look in the morning. Thanks for filing it 😄

**Comment by tido64** [comment]
Got a fix up. Let me know if you can verify it 😄

**Comment by Dirklectisch** [comment]
Thanks for the quick fix. Couldn't verify quickly (had some problems getting `deps-check` to build locally). But the change looks good to me.
