### ISSUE TITLE
JSX Support Issue

### ISSUE THREAD

**Issue by yushanwebdev** [microsoft/rnx-kit#2033]
Hi! 👋

Firstly, thanks for your work on this project! 🙂

### What happened?

Got this error after configuring the `@rnx-kit/babel-preset-metro-react-native` in the Babel Config as the only preset. Can you check?

Code - https://github.com/yushanwebdev/Instagram/tree/rnx-kit-jsx-issue

<img width="708" alt="Screenshot 2022-11-13 at 20 08 35" src="https://user-images.githubusercontent.com/25406148/201527464-54776798-7d75-4f3e-8e18-34c9e8cf9a64.png">

### Affected Package

@rnx-kit/babel-preset-metro-react-native

### Version

1.1.2

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 115.75 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.66.0 => 0.66.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Run this command in order.

1. yarn
2. cd iOS && pod install && cd ../
3. yarn run ios

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @yushanwebdev, I checked out your repro but I can't repro the issue:

```
% yarn react-native bundle --entry-file index.js --platform ios --bundle-output main.ios.jsbundle --dev true
yarn run v1.22.19
$ /~/Instagram/node_modules/.bin/react-native bundle --entry-file index.js --platform ios --bundle-output main.ios.jsbundle --dev true
                Welcome to Metro v0.72.3
              Fast - Scalable - Integrated


info Writing bundle output to:, main.ios.jsbundle
info Done writing bundle output
warn Assets destination folder is not set, skipping...
✨  Done in 3.76s.

% yarn react-native bundle --entry-file index.js --platform ios --bundle-output main.ios.jsbundle --dev false
yarn run v1.22.19
$ /~/Instagram/node_modules/.bin/react-native bundle --entry-file index.js --platform ios --bundle-output main.ios.jsbundle --dev false
                Welcome to Metro v0.72.3
              Fast - Scalable - Integrated


info Writing bundle output to:, main.ios.jsbundle
info Done writing bundle output
warn Assets destination folder is not set, skipping...
✨  Done in 7.22s.
```

Is it some caching issue?

**Comment by shivanshrajpoot-sc** [comment]
@tido64 I am facing the same issue, have tried resetting the cache but still the same result, old config is working fine.

**Comment by tido64** [comment]
@shivanshrajpoot-sc, I need a repro to investigate the issue. I can't reproduce the issue in the repo that OP set up.
