### ISSUE TITLE
"Unable to resolve module X from Y" with resolver-symlinks when linking an Npm library

### ISSUE THREAD

**Issue by AnatoleLucet** [microsoft/rnx-kit#2043]
### What happened?

I'm trying to link (`npm link ...`) a library to a react native project using `@rnx-kit/metro-resolver-symlinks` but Metro cannot resolve the linked library.

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.22

### Which platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
Not sure, but `npx react-native info` throws with `error: unknown command 'info'` on `v9.3.2`
```

### Steps to Reproduce

https://github.com/AnatoleLucet/rnx-kit-resolver-pnpm-repro

- `cd lib-monorepo`
- `pnpm i`
- `cd ../my-app`
- `npm i`
- `pnpm link ../lib-monorepo/lib`
- `npm run start`
- Then launch the app, and you should see `Unable to resolve module lib from ...`

Note that the lib is in its own Pnpm monorepo. Not sure if it really matters, but I included it anyway, as the lib is in a separate monorepo in my real app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @AnatoleLucet, looking at your `metro.config.js`, you're missing the [`watchFolders`](https://facebook.github.io/metro/docs/configuration/#watchfolders) field. You need to list all the paths that Metro may use to find files. I think if you add your repo root, it should work.

**Comment by AnatoleLucet** [comment]
Hi @tido64 thanks for replying. Unfortunately, I'm still running into the same error.

Current config:
```ts
module.exports = {
  projectRoot: __dirname,
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    resolveRequest: MetroSymlinksResolver(),
  },
  watchFolders: [
    __dirname,
    // just in case it's ignored or something
    path.join(__dirname, 'node_modules'),
  ],
};

```

**Comment by AnatoleLucet** [comment]
Seems to work :slightly_smiling_face:. So the lib-monorepo needs to be included manually in the `watchFolders`? Could it be possible to do this implicitly?

**Comment by tido64** [comment]
Yes, that's how Metro works. If you have a proper monorepo setup, [`@rnx-kit/metro-config`](https://github.com/microsoft/rnx-kit/tree/main/packages/metro-config#readme) will try to populate `watchFolders` for you.

**Comment by AnatoleLucet** [comment]
Unfortunate. I think it would be a nice addition to `@rnx-kit/metro-config` to run [this function](https://github.com/microsoft/rnx-kit/blob/main/packages/metro-config/src/index.js#L20-L60) on linked packages, just to make sure to include them and their dependencies if they are in another monorepo.  I think that would make stronger defaults.
If that's out of scope for this package, I think you can close this issue, I have my solution :slightly_smiling_face: 
Thanks!

**Comment by tido64** [comment]
I do think we want to scope the watch list to just the dependencies of the current app. The initial dev server startup is directly affected by how many files are being watched, so reducing it is good. I'm not sure if it's okay to tell users to restart Metro to pick up newly added packages. How often does that happen anyway? Maybe the answer is to support both.

In any case, I'll close this for now.
