### ISSUE TITLE
Babel preset for modern JS engines like V8

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#2054]
For React Native apps that use a modern JS engine (such as V8), we can drop a number of Babel plugins from the Metro preset and reduce the amount of polyfills needed to lower to ES5.

- Do we create an entirely new preset?
  - Compatibility table: https://kangax.github.io/compat-table/es6/
- Can we use [`@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-env.html)?
- How do we upstream this?

**Comment by afoxman** [comment]
How do you "target" a particular VM? Do you have one bundle built for V8 and another downlevel bundle for all other engines? This will need runtime/hosting support and make distribution a bit more complex, as the host will now need to request an engine-specific bundle.
