### ISSUE TITLE
Compiling JS Failed using `@rnx-kit/metro-serializer-esbuild`

### ISSUE THREAD

**Issue by joshuayoes** [microsoft/rnx-kit#2056]
### What happened?

In Ignite, we currently have `@rnx-kit/metro-resolver-symlinks` integrated into our vanilla react-native workflow. We would like to experiment with adding `@rnx-kit/metro-serializer-esbuild` to get faster compilation and tree shaking. 

However, I have been getting cryptic build errors when attempting to run the dev server

<img width="462" alt="Screen Shot 2022-11-30 at 12 20 40 PM" src="https://user-images.githubusercontent.com/37849890/204900047-90dd3919-cac6-489d-a1aa-9e4456931e6d.png">

See PR for more logs: https://github.com/infinitered/ignite/pull/1984

---

Attempted changes:
- apply settings to the [babel and metro config from [the usage example in the docs](https://microsoft.github.io/rnx-kit/docs/tools/metro-serializer-esbuild#usage)
- removing `export *` usage in Ignite from [known limitations section](https://microsoft.github.io/rnx-kit/docs/tools/metro-serializer-esbuild#known-limitations)
- updating the packages seems to [apply the suggestions from this issue](https://github.com/microsoft/rnx-kit/issues/1743)

### Affected Package

@rnx-kit/metro-serializer-esbuild

### Version

0.1.17

### Which platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
npx ignite-cli doctor
System
  platform           darwin                                                  
  arch               arm64                                                   
  cpu                10 cores      Apple M1 Max                              
  directory          boilerplate   /Users/joshuayoes/Code/ignite/boilerplate 

JavaScript (and globally-installed packages)
  node                      16.16.0                                   /Users/joshuayoes/.asdf/installs/nodejs/16.16.0/bin/node 
  npm                       7.24.2                                    /Users/joshuayoes/Code/ignite/node_modules/.bin/npm      
    eas-cli                 2.7.0                                                                                              
    expo-cli                6.0.6                                                                                              
    react-devtools-inline   4.26.1                                                                                             
    react-devtools          4.26.0                                                                                             
    sharp-cli               2.1.1                                                                                              
  yarn                      1.22.19                                   /Users/joshuayoes/.asdf/installs/nodejs/16.16.0/bin/yarn 
  pnpm                      7.5.2                                     /Users/joshuayoes/.asdf/installs/nodejs/16.16.0/bin/pnpm 
                            <no pnpm global package info available>                                                            
  expo                      46.0.17                                   managed                                                  

Ignite
  ignite-cli         8.4.2        /Users/joshuayoes/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/joshuayoes/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               11.0.16.1    /Users/joshuayoes/.asdf/shims/java    
  android home       -            /Users/joshuayoes/Library/Android/sdk 

iOS
  xcode              13.4.1     
  cocoapods          1.11.3       /Users/joshuayoes/.asdf/shims/pod 

Tools
  git                git version 2.37.3   /opt/homebrew/bin/git
```

### Steps to Reproduce

Pull down Ignite repo
```
git clone https://github.com/infinitered/ignite.git
cd ignite
```

Checkout PR https://github.com/infinitered/ignite/pull/1984
```
git checkout rnx-kit-esbuild
```

The Ignite repository has a cli in the root directory, but a fully functioning react-app in the `boilerplate` directory. Checkout, and start running
```
cd boilerplate
yarn install
yarn start
yarn ios
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @joshuayoes, switching back to JSC gave me some hints:

1. Babel was configured to disable import/export statement transforms. This should only be enabled when the esbuild plugin is active. This should be automatically detected, so unsetting it will get you past this issue.
2. In `metro.config.js`, the target is set to ES6, which is not fully supported by Hermes (it lacks support block scoping for instance). The default target is `hermes0.7.0` if you don't specify any, which should be good enough in your case.
3. Ultimately, the config needed for esbuild plugin is incompatible with dev server. More specifically, this means that we cannot use `esbuildTransformerConfig` during inner dev loop.

This is the diff I ended up with in order to make dev server working again: 

```diff
diff --git a/boilerplate/babel.config.js b/boilerplate/babel.config.js
index 8dda5d09..686164f8 100644
--- a/boilerplate/babel.config.js
+++ b/boilerplate/babel.config.js
@@ -13,7 +13,7 @@ const vanillaConfig = {
   presets: [
     [
       "@rnx-kit/babel-preset-metro-react-native",
-      { disableImportExportTransform: true, looseClassTransform: true },
+      { looseClassTransform: true },
     ],
   ],
   env: {
diff --git a/boilerplate/metro.config.js b/boilerplate/metro.config.js
index 4abd2505..62837ba3 100644
--- a/boilerplate/metro.config.js
+++ b/boilerplate/metro.config.js
@@ -51,8 +51,8 @@ if (isExpo) {
       },
       // esbuild custom serializer for speed and tree shaking
       // Note the caveats here: https://github.com/microsoft/rnx-kit/tree/main/packages/metro-serializer-esbuild#known-limitations
-      serializer: { customSerializer: MetroSerializer([], { target: "es6" }) },
-      transformer: esbuildTransformerConfig,
+      serializer: { customSerializer: MetroSerializer() },
+      //transformer: esbuildTransformerConfig,
     })
   })()
 }
```

In my opinion, the real issue here is figuring out how to set `transformer: esbuildTransformerConfig` only when bundling. I hope that helps.

**Comment by joshuayoes** [comment]
Thanks for taking a look at this! That is good to know that I should consider mainly using this plugin when bundling instead of on the dev server.

**Comment by joshuayoes** [comment]
Have you considered looking into `swc`? https://swc.rs/docs/configuration/compilation It is possible we may still be able to get similar speed gains, but have a more feature complete compiler for es5 code.

**Comment by tido64** [comment]
The reason we pursued esbuild is for tree shaking. The speed gains is just a bonus. Unless I missed something, swc doesn't do tree shaking.

That said, we have looked into it: https://github.com/microsoft/rnx-kit/tree/main/incubator/metro-swc-worker

This is a bit stale at this point, but I did an update about three months ago: https://github.com/tido64/rnx-kit/commit/5b4d2a9e4428b7eca5d4000b9ca26a918064ff5d

We did not see any performance gains in our testing. In fact, it's consistently slower. I suspect it's because of the JS plugin for collecting dependencies. Moving this to Rust might speed things up, but I don't have the time to investigate this further.

**Comment by joshuayoes** [comment]
Ah I see, that is good to know. It looks like they treeshaking as a part of their `swcpack` package, but it's still in development

**Comment by tido64** [comment]
> In my opinion, the real issue here is figuring out how to set `transformer: esbuildTransformerConfig` only when bundling. I hope that helps.

FWIW, this is handled by `@rnx-kit/cli`. I don't know if this is something you still want to pursue.

In any case, I'm closing this as the reported issues have been resolved. Feel free to [file new issues](https://github.com/microsoft/rnx-kit/issues/new/choose) or [open a discussion](https://github.com/microsoft/rnx-kit/discussions/new/choose).
