### ISSUE TITLE
@rnx-kit/align-deps error: 'alignDeps.requirements' cannot be empty

### ISSUE THREAD

**Issue by AlekhyaYalla** [microsoft/rnx-kit#2079]
While giving configs in the package.json, I'm providing only `requirements. development` requirements. But I'm getting the below error. 
Is this expected to give both the `production` & `development` in the `requirements` field?  

Here is the config in my package.json
```
 "rnx-kit": {
    "alignDeps": {
      "presets": [
        "my-custom-profiles"
      ],
      "requirements": {
        "development": [
          "react-native@0.68"
        ]
      },
      "capabilities": []
    }
  },
```
The error I'm facing:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/37897915/210058424-a17c799c-37b3-406f-866e-7576b3ca4a8b.png">

Thank you!

**Comment by tido64** [comment]
That is correct. If you have the same requirements for both development and production, you can collapse them:

```json
   "rnx-kit": {
    "alignDeps": {
      "presets": [
        "my-custom-profiles"
      ],
      "requirements": [
        "react-native@0.68"
      ],
      "capabilities": []
    }
```

I'll see if we can make the error message clearer.
