### ISSUE TITLE
Poor contrast ratio on hyperlinks

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#2089]
### What happened?

We need to do something about the contrast ratio on hyperlinks. They're barely visible here:

![image](https://user-images.githubusercontent.com/4123478/211280965-89bed9de-5463-44b6-a2f5-9aa635ac3d3c.png)

### Affected Package

@rnx-kit/docsite

### Version

n/a

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
n/a
```

### Steps to Reproduce

See https://microsoft.github.io/rnx-kit/docs/tools/overview

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dostonnabotov** [comment]
Hi, @tido64. I would be happy to pick this issue and solve it :)

We can either increase the contrast ratio by making its `background-color` darker or add `text-decoration: underline` to make it more visible. However, I think adding the underline might also affect links in other places as well if they use the same `class` or attribute. 

Let me know which one works best or other alternative options.

**Comment by tido64** [comment]
@kelset, what do you think?

**Comment by kelset** [comment]
thanks for offering @dostonnabotov! I think it'd be good to maybe make a PR with a test improvement and a couple screenshots for both light and dark mode

**Comment by dostonnabotov** [comment]
Hi, @kelset. 

I tried adding the underline to the links via Dev Tools, and it indeed helped to differentiate the text from the link. However, in terms of design perspective, it might not work well with the rest of the content.

Here is how it looks in light mode:

![updated version in light mode](https://user-images.githubusercontent.com/96492656/211524618-8ddafdc3-791c-468b-9efa-62a8a3632504.jpg)

And, in dark mode:

![updated version in dark mode](https://user-images.githubusercontent.com/96492656/211524998-48b12aaa-a0a1-4e71-bb32-3d0a53d684f7.png)

What do you think about it?

**Comment by kelset** [comment]
that approach looks fine to me, but also my skills in design are like -9999 so I'll let @tido64 decide if it's a viable solution - if he 👍 then we can move to a PR :)

**Comment by tido64** [comment]
I think the underlines look fine. I would also love to bump the contrast ratio up a bit if possible.
