### ISSUE TITLE
Broken link in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by dostonnabotov** [microsoft/rnx-kit#2090]
### What happened?

In the `CONTRIBUTING.md` file, there seems to be a broken link that directs to nowhere. 

After the "Contributor License Agreement", there is the "Requirements" section title. But, there is no "Code of Conduct" within or anywhere in the document as it's outlined in the table of contents.

![screenshot showing the broken link](https://user-images.githubusercontent.com/96492656/211296641-fbf03669-059b-4ee9-83d3-e161e5d6dc36.png)

### Affected Package

n/a

### Version

n/a

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
n/a
```

### Steps to Reproduce

See https://github.com/microsoft/rnx-kit/blob/main/CONTRIBUTING.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dostonnabotov** [comment]
I would be happy to pick this issue and solve it :) 

We can either remove the non-existent "Code of Conduct" link or add a new section with some descriptions for it. Let know which one is a good idea or any other alternative options.

**Comment by tido64** [comment]
@kelset, what do you think? Is it sufficient to a section that links to the CoC?

**Comment by kelset** [comment]
yeah we can just remove the bullet point entry, the CoC is linked right above in "As a contributor, you're expected to follow the [code of conduct](https://github.com/microsoft/rnx-kit/blob/main/CODE_OF_CONDUCT.md)."
