### ISSUE TITLE
metro-config should have an option to not populate watchFolders

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/rnx-kit#2143]
### What happened?

Sometimes you want to be more precise about what folders are added to `watchFolders`.  Currently `metro-config` always adds all packages within the whole repo.

A new option should be added to `metro-config` to opt out of the auto population of `watchFolders`

### Affected Package

@rnx-kit/metro-config

### Version

1.3.4

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [X] macOS
- [X] Windows

### System Information

```true
N/A
```

### Steps to Reproduce

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
I've just had a look and it turns out we already support this. If you set `watchFolders` in the config you pass to `makeMetroConfig`, it will override the auto-populated one. I've submitted a change to skip the auto-population to save some time since it was just discarded.
