### ISSUE TITLE
Mis-aligned dependencies which are not mentioned in capabilities section in config, are not throwing error when --write flag is not given in the command.

### ISSUE THREAD

**Issue by knarwani** [microsoft/rnx-kit#2170]
### What happened?

Let's assume my package have only 2 dependencies say `react` and `typescript`. In one of my profiles, I have `react` dependency added in capabilities section/field inside rnx-kit config of my package.json. Whereas `typescript`  is not added in capabilities. Now when I run the command `yarn rnx-align-deps --presets "path-to-my-preset" --requirements react-native@0.68`, I notice that tool is only able to detect the misalignment in `react` dependency where expected output should be that it should have detected misalignment in both the dependencies (react & typescript) which used to be the behaviour in rnx-kit/dep-check. Once the alignment of `react` dependency is corrected/fixed, tool is able to detect the `typescript` misalignment.

So, conclusion is that rnx-kit tool is able to detect both the dependencies misalignment, but it takes two iterations to do that.

Opposite is the case when I run the command with --write flag. In first run it will align the dependencies which are not defined in capabilities and in next run it will align those dependencies which are defined in capabilities.

### Affected Package

@rnx-kit/align-deps

### Version

^2.0.3

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### System Information

```true
NA
```

### Steps to Reproduce

Run `yarn rnx-align-deps --presets "path-to-my-preset" --requirements react-native@0.68` in a monorepo with the setup of dependencies defined above.

```
// package.json
{
    //rest of the package.json
    "dependencies": {
            "react": "~15.0.0",
            "typescript": "4.0.0"
      },
      "rnx-kit": {
           "align-deps": {
                 "presets": [ "path-to-my-preset" ],
                 "requirements": ["react-native@0.68"],
                  "capabilities": ["react"]
              }
         }
    }
```
```
// my-preset.js
module.exports = {
        "profile-name": {
                 "react-native": {
                       name: "react-native",
                       version: "0.68.0"
                  },
                 "react": {
                       name: "react",
                       version: "~17.0.2"
                  },
                  typescript: {
                       name: "typescript",
                       version: "4.9.3"
                  },
         }
}
```
now by running the command `yarn rnx-align-deps --presets my-presets.js --requirements react-native@0.68` we can see that only `react` dependency will get aligned to 17.0.1. And after correcting `react` we have to again run the same command to align the `typescript` dependency to 4.9.3.

Screenshot of the command line after first tun of the command. Here we can see that `typescript` is still at 4.0.0.
<img width="739" alt="first run" src="https://user-images.githubusercontent.com/110807392/216254475-d75f714c-4bfe-4c60-819e-6dbfb01b6ee3.png">

Screenshot of the command line after second tun of the command. Now we can see that `typescript` error is shown.
<img width="739" alt="second run" src="https://user-images.githubusercontent.com/110807392/216254643-a1f4ef62-e82f-465d-9f1d-fdae25a99181.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by knarwani** [comment]
Thanks for the quick fix.

**Comment by tido64** [comment]
FYI, just discovered a bug with this. We've got a fix here: https://github.com/microsoft/rnx-kit/pull/2175
