### ISSUE TITLE
metro: add support for `unstable_enablePackageExports `

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#2255]
Metro 0.75.1 will be the first version with support for exports map: https://github.com/facebook/metro/issues/670#issuecomment-1434510835

We need to make sure that when this flag is enabled, our plugins will also honor it.

**Comment by The-White-Fang** [comment]
I am not sure if I was using it correctly but for me, this option was not working when used with `@rnx-kit/metro-resolver-symlinks`

I was using the following config
```
const { makeMetroConfig } = require('@rnx-kit/metro-config');
const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks');

module.exports = makeMetroConfig({
	projectRoot: __dirname,
	resolver: {
		resolveRequest: MetroSymlinksResolver(),
		unstable_enablePackageExports: true,
	},
});
```

After removing `@rnx-kit/metro-resolver-symlinks` and replacing it with `unstable_enableSymlinks` everything started working fine again.

This is the updated config
```
const { makeMetroConfig } = require('@rnx-kit/metro-config');

module.exports = makeMetroConfig({
	projectRoot: __dirname,
	resolver: {
		unstable_enableSymlinks: true,
		unstable_enablePackageExports: true,
	},
});
```

**Comment by tido64** [comment]
> I am not sure if I was using it correctly but for me, this option was not working when used with `@rnx-kit/metro-resolver-symlinks`

Hi, can you open a bug report here: https://github.com/microsoft/rnx-kit/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

We need more details to help you investigate this. When you say "working fine again", what exactly didn't work before? Did it crash? Did the bundling fail? Did the app fail to run? And most importantly, we want a minimal repro. If we cannot reproduce the error you're seeing, we cannot help you.
