### ISSUE TITLE
replacing "react-native bundle" calls by "react-native rnx-bundle" results in huge console logs

### ISSUE THREAD

**Issue by Thanaen** [microsoft/rnx-kit#2419]
### What happened?

Hello,

I have set up rnx-kit to bundle my application.
I replaced the `react-native start` scripts with `react-native rnx-start`, and it works perfectly.

I also wanted to replace the calls to `react-native bundle` with `react-native rnx-bundle`. (For Android, I used `bundleCommand = "rnx-bundle"` in build.gradle, and for iOS I used `export BUNDLE_COMMAND=rnx-bundle` in the bundle phase on XCode.

For Android, this works, but there is a problem: the whole generated js bundle is logged in the console, and I suspect it is logged several times in a row because my log file was over 300 megabytes at the end of the build.

For iOS, when trying to archive, it also logs a lot of lines related to the source code, but the bundle step never finishes (as if the bundle script was still in "waiting for input" mode).

So several questions:
- Can we use `rnx-bundle` as a drop-in replacement for `react-native bundle`?
- Did I forget some parameters that would have allowed to avoid these logs ?

If we can't replace `react-native bundle` directly by `react-native rnx-bundle`, how should we use it?

### Affected Package

@rnx-kit/cli

### Version

0.16.9

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
For some reasons, running "npx react-native info" returns "unknown command 'info'"
```

### Steps to Reproduce

1. Create a new react-native project
2. Setup rnx-kit bundling (https://microsoft.github.io/rnx-kit/docs/guides/bundling#setting-up-the-tools)
3. In "./android/app/build.gradle", set "bundleCommand" to "rnx-bundle"
4. For iOS, in XCode, add this line to the bundle phase script: "export BUNDLE_COMMAND=rnx-bundle"
5. Generate an Android APK, and an iOS Archive

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rag0n** [comment]
Same issue for me

**Comment by tido64** [comment]
Do you use Hermes? Do these "huge console logs" come from the Hermes compiler? If so, try this workaround to disable warnings: https://github.com/microsoft/rnx-kit/issues/2416#issuecomment-1547309239

We can't control the console output of Hermes. If you think this is a real issue, you should file it on their GitHub instead.

**Comment by Thanaen** [comment]
I do use Hermes!
I will try that, thanks! Do you think this is what is blocking the bundle in XCode? (maybe I should create a new issue for this)

**Comment by tido64** [comment]
For the blocking bundle issue, do you have a repro? I've not seen this myself so having a repro would help us investigate.

**Comment by Thanaen** [comment]
At this time, I did not publish a repro project.
I might try to put one up next week.

The repro steps are pretty simple:
- In the bundle phase of XCode, add the line `export BUNDLE_COMMAND=rnx-bundle`, then generate an archive.

I'll try to set one up as soon as I have some free time (and a Macbook available!)

**Comment by tido64** [comment]
For fix and workaround, see https://github.com/microsoft/rnx-kit/issues/2416#issuecomment-1558774451.
