### ISSUE TITLE
Dependency Manager Customizations

### ISSUE THREAD

**Issue by Mohideen-Abdul-Kadar** [microsoft/rnx-kit#2631]
AILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\KADAR\React-Native\mellow-plex-mobile\node_modules\@react-native-async-storage\async-storage\android\build.gradle' line: 85

* What went wrong:
A problem occurred evaluating project ':react-native-async-storage_async-storage'.
> Plugin with id 'com.facebook.react' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-async-storage_async-storage'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by kelset** [comment]
invalid issue
