### ISSUE TITLE
Importing files outside root directory while using metro-plugin-typescript

### ISSUE THREAD

**Issue by karimb11** [microsoft/rnx-kit#2953]
### What happened?

When trying to use files outside the current root project (Using babel module-resolver aliases), this error occurrs:

error: Error: Cannot find project root for source file PATH_TO_PROJECT\shared\index.ts'
    at findProjectRoot (PATH_TO_PROJECT\mobile\node_modules\@rnx-kit\metro-plugin-typescript\lib\projectCache.js:58:19)
    at Object.getProjectInfo (PATH_TO_PROJECT\mobile\node_modules\@rnx-kit\metro-plugin-typescript\lib\projectCache.js:112:22)

PATH_TO_PROJECT is just a placeholder for my actual full path.

For information, using metro without rnx-kit works

### Affected Package

@rnx-kit\metro-plugin-typescript

### Version

0.4.4

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
This is a pure JavaScript issue.
```

### Steps to Reproduce

- Import a file that is outside the current project's root directory, using babel's module-resolver plugin "alias" option.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
What does your `tsconfig.json` look like? Does it match with how you've configured `module-resolver`?

**Comment by karimb11** [comment]
@tido64 Yes the aliases are similar, the proof is that when I added the hack, the build worked correctly. Also the logic that exists in createProjectCache() makes it clear why this fails. You have a file that is outside the root directory which is being compared with the the root directory using .startsWith. That check will always fail.

For info, this issue does not occur with stock Metro bundler.

**Comment by karimb11** [comment]
Example babel configuration

```
module.exports = {
    presets: [ "@rnx-kit/babel-preset-metro-react-native" ],

    plugins: [
        [
            "module-resolver",
            {
                root: [ "." ],

                extensions: [ ".ts", ".tsx", ".json" ],

                alias: {
                    "shared": "../shared"

                }
            }
        ]
    ]
};
```

Example tsconfig configuration

```
{
    "extends": "@react-native/typescript-config/tsconfig.json",

    "compilerOptions": {
        "baseUrl": "./src",

        "paths": {
            "shared/*": [ "../../shared/*" ]
        }
    },

    "include": [
        "./src",
        "../shared"
    ],

    "exclude": [
        "./node_modules"
    ]
}
```

**Comment by tido64** [comment]
As far as I can tell, each root folder is treated as a project. If a folder contains a `tsconfig.json`, it is treated as a TS project and its files will be type-checked by the TypeScript service. Otherwise, the folder is treated as a JS project and will not be type-checked.

cc @afoxman in case I'm mistaken.

**Comment by karimb11** [comment]
@tido64 I see, what strategy would one have to follow to have the  same tsconfig apply to these shared projects, without having to duplicate the file twice?

**Comment by tido64** [comment]
Use shared configs: https://www.typescriptlang.org/tsconfig#extends
