### ISSUE TITLE
404 Not Found [npx fix-dependencies]

### ISSUE THREAD

**Issue by kunalSBasic** [microsoft/rnx-kit#3206]
### What happened?

I was following the docs as mentioned [https://microsoft.github.io/rnx-kit/docs/guides/dependency-management](url)
Although while running the command `npx fix-dependencies` I got the error of which I am attaching the screenshot below.
<img width="1334" alt="Screenshot 2024-06-27 at 10 18 54 AM" src="https://github.com/microsoft/rnx-kit/assets/109348919/1a102c1c-ea96-48f6-964a-f4b1e77da1c8">

### Affected Package

fix-dependencies 

### Version

"react-native": "0.72.6"

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 196.88 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.1
    path: ~/.nvm/versions/node/v16.20.1/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 6.14.18
    path: ~/.nvm/versions/node/v16.20.1/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.2
      - 34.0.0
    System Images:
      - android-28 | Google APIs ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ATD ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to Reproduce

In the react-native project at root run the command `npm add --save-dev @rnx-kit/align-deps`
Then add the following scripts command in package.json:
```
 "scripts": {
    "check-dependencies": "rnx-align-deps",
    "fix-dependencies": "rnx-align-deps --write"
  }
```
Then run the command `npx rnx-align-deps --init app`
At last run `npx fix-dependencies` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
To run a script, you need to run `npm run <script>`. You should read the npm documentation here: https://docs.npmjs.com/cli/v10/commands/npm-run-script

As this issue is unrelated to rnx-kit, I'm closing it.
