### ISSUE TITLE
Use @react-native-communty/cli-plugin-metro project to bundling, and remove custom code in CLI and related packages

### ISSUE THREAD

**Issue by afoxman** [microsoft/rnx-kit#328]
I created @rnx-kit/metro-service from code in @react-native-community/cli to give us immediate access to calling Metro programmatically.

Check with @react-native-community/cli devs -- grabbou specifically -- about factoring out the code that talks to metro.

**Comment by afoxman** [comment]
Still need to remove the custom code I added (copied) from @rnc community project. Now that it's all wrapped up and exposed through CLI, we should use that instead.

**Comment by tido64** [comment]
For future reference, `@react-native-community/cli@6.1.0` is equivalent to `react-native@0.66`.

**Comment by kelset** [comment]
headsup: things have been moving around -> https://github.com/facebook/react-native/pull/38795
