### ISSUE TITLE
[@rnx-kit/tools-react-native] "loadContext" throw an error when using an old version of "@react-native-community/cli"

### ISSUE THREAD

**Issue by SAMYJ1** [microsoft/rnx-kit#3295]
### What happened?

The exported function "loadContext" throw an error when using an old version of "@react-native-community/cli" (4.x in my project) in react-native project__

### Affected Package

@rnx-kit/tools-react-native

### Version

1.4.0

### Which platforms are you seeing this issue on?

- [ ] Android
- [x] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
// @rnx-kit/tools-react-native/lib/context.js#40
function loadContext(root = process.cwd()) {
  const state = (0, cache_1.getCurrentState)(root);
  if (state === (0, cache_1.getSavedState)(root)) {
    const config = (0, cache_1.loadConfigFromCache)(root);
    if (config) {
      return config;
    }
  }
  const rncli = resolveCommunityCLI(root);
  const { loadConfig } = require(rncli);
  // FIXME: no "loadConfig" been exported in version 4.x of @react-native-community/cli 
  const config = loadConfig.length === 1
    ? loadConfig({ projectRoot: root })
    : loadConfig(root);
  (0, cache_1.saveConfigToCache)(root, state, config);
  return config;
}

And there is the error:
TypeError: Cannot read properties of undefined (reading 'length')
    at loadContext (/Users/mayijian/work/test/max-test-1723624478436/node_modules/@rnx-kit/tools-react-native/lib/context.js:51:29)
    at getAvailablePlatformsUncached (/Users/mayijian/work/test/max-test-1723624478436/node_modules/@rnx-kit/tools-react-native/lib/platform.js:46:53
)
    at /Users/mayijian/work/test/max-test-1723624478436/node_modules/@rnx-kit/tools-react-native/lib/platform.js:34:27
...
```

### Steps to Reproduce

nope

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi, thanks for filing this. `loadConfig` is exported as of 7.0. I had simply forgotten that detail when I refactored this package earlier. It would be great if you could verify the fix I've just submitted.

**Comment by SAMYJ1** [comment]
> Hi, thanks for filing this. `loadConfig` is exported as of 7.0. I had simply forgotten that detail when I refactored this package earlier. It would be great if you could verify the fix I've just submitted.

Thanks for your fix, but it still crashed when I using @react-native-community/cli@7.x or lower. The package "@react-native-community/cli-config" is imported by "@react-native-community/cli"  as of 8.x. It may throw an error when require that.

**Comment by tido64** [comment]
> Thanks for your fix, but it still crashed when I using @react-native-community/cli@7.x or lower. The package "@react-native-community/cli-config" is imported by "@react-native-community/cli" as of 8.x. It may throw an error when require that.

Thanks for testing it! It looks like we do have to bring back the old implementation. I was hoping we didn't have to. We should now fall back to it if we can't find `loadConfig`. Would you mind trying the latest iteration?

**Comment by SAMYJ1** [comment]
> > Thanks for your fix, but it still crashed when I using @react-native-community/[cli@7.x](mailto:cli@7.x) or lower. The package "@react-native-community/cli-config" is imported by "@react-native-community/cli" as of 8.x. It may throw an error when require that.
> 
> Thanks for testing it! It looks like we do have to bring back the old implementation. I was hoping we didn't have to. We should now fall back to it if we can't find `loadConfig`. Would you mind trying the latest iteration?

It works fine with that iteration, thanks!
