### ISSUE TITLE
Bundle sever should react to changes in any in-repo dependency

### ISSUE THREAD

**Issue by afoxman** [microsoft/rnx-kit#448]
When a metro server is running, it *should* react to changes in any dependent package in the repo, not just the app package. 

Make sure that typescript validation is happening on these dependencies -- specifically, on the source .ts[x] files.

_Originally posted by @afoxman in https://github.com/microsoft/rnx-kit/issues/173#issuecomment-829501383_

**Comment by afoxman** [comment]
I think the babel path remapper we have will make this possible.

**Comment by tido64** [comment]
Metro should already be watching everything, particularly because it can only resolve files that are being watched.
