### ISSUE TITLE
Upstream Metro type libraries

### ISSUE THREAD

**Issue by afoxman** [microsoft/rnx-kit#473]
### Description

The monorepo has a collection of @types libraries for Metro packages. These should be upstreamed to definitely typed.

Also, there are more types to be added. Take another look at `flow2dts` (and other similar projects) to assist with this.

### Your environment

- Affected package:
- Version:
- Tested platforms:
  - [ ] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- System information:
  ```
  # Run `npx react-native info` and paste the output here
  ```

**Comment by tido64** [comment]
PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57006
