### ISSUE TITLE
RFC: rename `dep-check` to something else

### ISSUE THREAD

**Issue by kelset** [microsoft/rnx-kit#484]
I'm opening this issue because I want to start a conversation on changing the name of one of the tools we provide, currently named `dep-check`.

I've been thinking about this for a while because of the name collision with a tool in the same space called [`depcheck`](https://github.com/depcheck/depcheck)... which kind of works in the same problem space too, so there could be situation in which both tools might be used in the same codebase.

This topic has also been brought up by @afoxman [here](https://github.com/microsoft/rnx-kit/pull/455#discussion_r683055206):
> The name dep-check is getting stretched awfully thin at this point... maybe a more general name since it can do so much to handle dependencies? Or several commands?

And I agree - `dep-check` is now a defacto incredibly powerful tool that:
* keeps dependencies versions aligned across packages and repos, based on curated profiles
* fixes package.json configurations (puts deps, devDeps, peerDeps correctly)
* addresses missing dependencies
* can do these things even for non RN packages
* (and I'm probably forgetting something)

So I would propose that we should come up with a better name for it.

Here are some quick ideas to use as baseline for coming up with the new name, and attached is the npmjs search for that term (to validate over time that the name wasn't taken/stolen since the moment I'm writing this).
* `tailor` - [npmjs search](https://www.npmjs.com/search?q=tailor)
* `deps-tailor` - [npmjs search](https://www.npmjs.com/search?q=deps-tailor)
* `align-deps` - [npmjs search](https://www.npmjs.com/search?q=align-deps)
* `deps-fixer` - [npmjs search](https://www.npmjs.com/search?q=deps-fixer)
* `shape-deps` - [npmjs search](https://www.npmjs.com/search?q=shape-deps)
* `deps-shaper` - [npmjs search](https://www.npmjs.com/search?q=deps-shaper)

The only minor point about this, is that I would wait to make this happen to >= mid September, since on Sept 1/2 there's RNEU where we announce and talk about it 😅

**Comment by kelset** [comment]
Quick follow up, the name `dep-check` is also used for [this tool](https://opensourcelibs.com/lib/dep_check):
> Checks your (Flutter) dependencies for the latest version
🤣

**Comment by afoxman** [comment]
dep-check is becoming important an important tool outside of react-native projects. I expect it will move out to another tools repo in the near future (months), and that will be the time to give it a new name. The react-native profiles will still live here and will be paired with the-artist-formerly-known-as-dep-check through our tools and config.

**Comment by afoxman** [comment]
Closing this since there's no work in this repo. We can rename it when it moves to another repo.

**Comment by tido64** [comment]
Reopening this since there's more interest around this now. I'd also like to propose `dependacop` as possible name (I think @dzearing suggested it some time ago).

**Comment by afoxman** [comment]
package-lint
align-packages

**Comment by ecreeth** [comment]
😎deps-version-health

**Comment by kelset** [comment]
Closing this since now it's part of the RFC here: https://github.com/microsoft/rnx-kit/pull/1757 please add your comments there!
