### ISSUE TITLE
We should provide a way to have metro to not watch all the roots

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/rnx-kit#536]
Metro by default will watch all the files within all the roots.  This means that generally metro ends up watching all the files within node_modules. 

The haste-map built internally by metro currently only has a single flag to control if the entire map is watched.  Really this needs to be expanded to have a config to say which folders should be watched, rather than always watching all the roots.
https://github.com/facebook/metro/blob/96fb6e904e1660b37f4d1f5353ca1e5477c4afbf/packages/metro/src/node-haste/DependencyGraph.js#L165

**Comment by afoxman** [comment]
Metro PR has been submitted: https://github.com/facebook/metro/pull/701

**Comment by afoxman** [comment]
Going in a different direction with this work. See #1289 for details.
