### ISSUE TITLE
metro-resolver-symlinks throws error because of excludeExtraCopiesOf

### ISSUE THREAD

**Issue by icesuicune** [microsoft/rnx-kit#585]
### What happened?

Made a brand new react native project with the react native typescript template. Installed dependencies with pnpm and added some rnx-kit stuff.

Added the symlink resolver to metro.config.js.

First error I was getting was like 
`MetroSymlinksResolver is not a function.`
This was from the example in the readme which I copy pasted. I had to use `const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks').default` instead.

After that I started getting `react could not be found.`

I followed the exception down to around here:
```
 * @param {string} name
 * @param {string=} projectRoot
 * @returns {string | undefined}
 */
function resolveModule(name, projectRoot) {
  const { findPackageDependencyDir } = require("@rnx-kit/tools-node/package");
  return findPackageDependencyDir(
    { name },
    { startDir: projectRoot, allowSymlinks: false }
  );
}
```
where allowSymlinks is hardcoded as false in @rnx-kit/metro-config.

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.2

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.

Well, something is messed up here.
```

### Steps to Reproduce

[Repro repo](https://github.com/icesuicune/rnxSymlinkErrorRepro)
pnpm install -g
cd MyApp
pnpm install
pnpx rnx-kit --config ./metro.config.js

The repo is basically the react native generated template, with bits taken from the /test app package in this project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for reporting this. I was able to repro, and will work on a solution.
