### ISSUE TITLE
detectDuplicateDependencies and detectCyclicDependencies ignore false setting

### ISSUE THREAD

**Issue by simarmol** [microsoft/rnx-kit#605]
So i am trying to get rnx-kit working on a pre-existing repo, and found that I couldn't seem to disable cyclic dependency detection and duplicate dependency detection. I have them configured in my package.json, and other config values seem to get picked up by the bundler. Even the ignoredModules array gets used properly. However, setting the values to false or removing the properties entirely from the rnx-kit section doesn't do anything.

Here is a chunk of my configuration:
```json
"rnx-kit": {
    "reactNativeVersion": "^0.63",
    "kitType": "app",
    "bundle": {
      "entryPath": "index.js",
      "distPath": "dist",
      "assetsPath": "dist",
      "detectCyclicDependencies": false,
      "bundlePrefix": "main",
      "typescriptValidation": false,
      "detectDuplicateDependencies": {
        "ignoredModules": [
          "react-is", "react-native-modal", "postcss-value-parser", "react-native-device-info", "domelementtype", "entities", "react-native-svg", "escape-string-regexp", "color-name", "fbjs", "eventemitter3", "tslib", "lodash-es", "reselect", "@react-navigation/core", "hoist-non-react-statics", "@react-navigation/native", "react-native-vector-icons", "color", "css-to-react-native"
        ]
      }
    },
    "server": {
      "detectDuplicateDependencies": {
        "ignoredModules": [
          "react-is"
        ]
      },
      "detectCyclicDependencies": false
    },
```

Been testing the config by just running rnx-bundle repeatedly. As you can see I had to add packages to the ignore array by hand, at which point I instead started getting cyclic dependency errors too, despite having disabled that.

I can spin up a repro repo if need be, but I took a quick look and found this:

https://github.com/microsoft/rnx-kit/blob/7200426250deb288fb38a3d8da91bb74a0e71437/packages/cli/src/metro-config.ts#L104-L113

So... am I misunderstanding something or are the plugins getting enabled as long as a boolean is provided? Regardless of whether it's true or false? Or is there another check further downstream on the value of the booleans?

**Comment by simarmol** [comment]
Well, modified it locally in my node_modules and now it seems to work like I'd expect.

```js
    if (typeof detectDuplicateDependencies === "boolean" && detectDuplicateDependencies) {
        plugins.push((0, metro_plugin_duplicates_checker_1.DuplicateDependencies)());
    }
    else if (detectCyclicDependencies === true) {
        plugins.push((0, metro_plugin_duplicates_checker_1.DuplicateDependencies)(detectDuplicateDependencies));
    }
    if (detectCyclicDependencies === true) {
        plugins.push((0, metro_plugin_cyclic_dependencies_detector_1.CyclicDependencies)());
    }
    else if (typeof detectCyclicDependencies === "object") {
        plugins.push((0, metro_plugin_cyclic_dependencies_detector_1.CyclicDependencies)(detectCyclicDependencies));
    }
```

**Comment by tido64** [comment]
Thanks for investigating and reporting this issue. I have PR with a fix. It would be great if you could give it a go and verify that it fixes the issue.
