### ISSUE TITLE
using pnpm and metroResolverSymlink gets unable to resolve module interopRequireDefault during server

### ISSUE THREAD

**Issue by icesuicune** [microsoft/rnx-kit#606]
### What happened?

Getting this error now:
```
> react-native rnx-start "clean"


                        #######
                   ################
                #########     #########
            #########             ##########
        #########        ######        #########      
       ##########################################     
      #####      #####################       #####    
      #####          ##############          #####    
      #####    ###       ######       ###    #####    
      #####    #######            #######    #####    
      #####    ###########    ###########    #####    
      #####    ##########################    #####    
      #####    ##########################    #####    
      #####      ######################     ######    
       ######        #############        #######     
         #########        ####       #########        
              #########          #########
                  ######### #########
                       #########


                    Welcome to Metro!
              Fast - Scalable - Integrated


To reload the app press 'r'
To open developer menu press 'd'
To quit, press 'control-c'
 BUNDLE  src/index.js

error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from D:\OneDrive\Code\repos\RNSomething\MyApp\src\index.js: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules
  D:\OneDrive\Code\repos\RNSomething\node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
> 1 | /**
  2 |  * @format
  3 |  */
  4 |
    at ModuleResolver.resolveDependency (D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules\.pnpm\metro@0.66.2\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules\.pnpm\metro@0.66.2\node_modules\metro\src\node-haste\DependencyGraph.js:288:43)
    at Object.resolve (D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules\.pnpm\metro@0.66.2\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules\.pnpm\metro@0.66.2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules\.pnpm\metro@0.66.2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules\.pnpm\metro@0.66.2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules\.pnpm\metro@0.66.2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
    at async traverseDependenciesForSingleFile (D:\OneDrive\Code\repos\RNSomething\MyApp\node_modules\.pnpm\metro@0.66.2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:13
```

The file is where I'd expect it to be, so I'm not sure what is wrong now.

I tried installing watchman at one point and started getting an even weirder error, so I went to check the RN docs for setting up your environment, and the windows setup does not involve installing watchman. So uninstalled that and went back to this error.

Most of the sample repo has been copied right out of the test app in this repo.

Is there some config for the symlink resolver that would fix this? I poked around a bit at the files in the stack trace, and everything seems fine up until the point where it tries resolving the module path/name and fails, even though it's looking in the correct directory.

I'm getting a different error when I try bundling instead, so maybe the real error is just being obfuscated.

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.3

### Which platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
➜  pnpx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 13.00 GB / 31.95 GB
  Binaries:
    Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2, 31.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64    
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31205.134 (Visual Studio Professional 2019)
  Languages:
    Java: javac 15
  npmPackages:
    @react-native-community/cli: ^6.0.0-0 => 6.0.0
    react: 17.0.2 => 17.0.2
    react-native: ^0.65.0-0 => 0.65.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

[Repro repo](https://github.com/icesuicune/rnxSymlinkErrorRepro)

Steps:
```
npm install -g pnpm
git clone https://github.com/icesuicune/rnxSymlinkErrorRepro.git
cd rnxSymlinkErrorRepro/MyApp
pnpm install
pnpm run android
```

Don't own a Mac that doesn't belong to work so haven't tried running ios.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Can you try adding your app folder to `watchFolders`:
```diff
diff --git a/MyApp/metro.config.js b/MyApp/metro.config.js
index cc134d4..d8929d7 100644
--- a/MyApp/metro.config.js
+++ b/MyApp/metro.config.js
@@ -7,4 +7,7 @@ module.exports = makeMetroConfig({
   resolver: {
     resolveRequest: MetroSymlinksResolver(),
   },
+  watchFolders: [
+    __dirname
+  ]
 });
```
Metro only watches the path you specified at `projectRoot`. Since it's no longer the package root, you need to add it manually to `watchFolders`.

**Comment by icesuicune** [comment]
I had had tried a few different project roots but wasn't seeing any changes. That said, I seem to have caused this myself by overwriting my own config.  I think I had the project root set in three places.

In the package.json scripts I had
```json
    "start": "react-native rnx-start --project-root src"
...
 "server": {
      "entryPath": "src/index.js",
      "detectDuplicateDependencies": {
        "ignoredModules": [
          "react-is"
        ]
      }
```
but I was only modifying the metro config project root value. I'm assuming the command line argument was overriding my root in metro.config. And entry path is only a valid property for the bundle config, and not the server? Or maybe not? I don't suppose there's a json schema definition or vscode extension that will help me out with the valid values for the rnx-kit section in package.json?

My app now bundles to 99% and then crashes violently with no error, so problem solved? Thanks for the help.

**Comment by tido64** [comment]
There's some documentation here: https://github.com/microsoft/rnx-kit/tree/main/packages/cli#readme

The gist is that you should provide most things in the config, and only use command line args when you need to override something. It's a good idea to have intellisense though.

> My app now bundles to 99% and then crashes violently with no error

I was unable to repro this locally. Do you have a stack trace? Did you try using Node 14?

**Comment by icesuicune** [comment]
I ended up debugging it in android studio, and it seemed to be some odd initialization error. Supposedly some issue with the emulator configuration itself. I abandoned looking at it for the time being since I had a device on hand to test with.
