### ISSUE TITLE
Configuration from metro.config.js get overridden by CLI argument defaults

### ISSUE THREAD

**Issue by icesuicune** [microsoft/rnx-kit#631]
### What happened?

I was moving some files around in an empty project and started getting a haste map error around the lines of ‘MyApp/src could not be found’. At some point, I had added a MyApp/src dir and moved index.js and App.tax in there, then moved them back out and deleted the folder. Thinking it was some weird cache issue, I spent a couple of days trying every trick in the book to clear my npm, pnpm, watchman, metro, and cradle caches.

Eventually I started stepping through the metro server code, trying to find out what cache file I had missed. Eventually though, I found out that the overriding value came from rnx kit.

I had my setting defined as follows:
In package.json, I did NOT define a property for the rnx kit server and bundle project root.
In my tsconfig, I did not specify any base urls, root dirs, etc.
In my metro config, I had my project root defined as __dirname (./MyApp).
The command I ran was react-native rnx-start, with no arguments, in ./MyApp.

What I expected to happen was that the override order was CLI args > package json rnxkit config > metro config. Since I left the first two empty, I expected the third to take effect.

However, it seems that the default values for the cli are taking precedence, over defined values in metro config. Seems to be in the below file?

https://github.com/microsoft/rnx-kit/blob/main/packages/config/src/getServerConfig.ts

I guess if this is expected behavior, it would be nice if the docs explicitly mentioned that certain values on metro.config will essentially be ignored, while others will work. Maybe a CLI warning too. Or maybe specify that it’s a default? Perhaps this is something inherited from metro, but if they have a default value for it I couldn’t find it.

I would also like to note that the react native community template for typescript doesn’t come with a src folder.

https://github.com/react-native-community/react-native-template-typescript/tree/master/template

I guess it’s a bit of an edge case since most everyone will make a src folder, but it is pretty confusing if someone tries to set up all their config and get it running before adding anything to the app template.

### Affected Package

@rnx-kit/cli

### Version

Latest?

### Which platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
➜  pnpx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 13.00 GB / 31.95 GB
  Binaries:
    Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2, 31.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64    
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31205.134 (Visual Studio Professional 2019)
  Languages:
    Java: javac 15
  npmPackages:
    @react-native-community/cli: ^6.0.0-0 => 6.0.0
    react: 17.0.2 => 17.0.2
    react-native: ^0.65.0-0 => 0.65.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Oops, forgot to push to the repro repo. Will do it tomorrow morning.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Sorry this took so long to fix. I have a PR with a fix. If you have time, it would be great if you could check it out. Thanks again for reporting this ❤️
