### ISSUE TITLE
@react-native-clipboard/clipboard

### ISSUE THREAD

**Issue by safaiyeh** [microsoft/rnx-kit#844]
### What happened?

When using generating the dep diff for RN 0.65 we get this result

```
-     "@react-native-clipboard/clipboard": "^1.9.0",
+     "@react-native-clipboard/clipboard": "^1.8.4",
```

A couple things, 1.9.0 resolves some 0.65 emitter warnings so it could be deemed required for 0.65. Also should dep kit be strict to downgrade a package? 

### Affected Package

@rnx-kit/dep-check

### Version

1.8.18

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 15.27 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/Jason.Safaiyeh/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Users/Jason.Safaiyeh/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.65.0-0 => 0.65.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

1. Create a React Native project with v0.65
2. Add "@react-native-clipboard/clipboard": "^1.9.0" to dependencies
3. Run dep kit check
4. Makes suggestion to downgrade.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for reporting this, @safaiyeh! I skimmed the change log and bumped clipboard for 0.64 and 0.65.

> Also should dep kit be strict to downgrade a package?

In my experience, having everyone using the same version string avoids introducing duplicates. In this case, you can still install 1.9.0 for those essential fixes without introducing accidentally introducing a second copy of clipboard at 1.8.4.

**Comment by safaiyeh** [comment]
Thanks @tido64! Looking at the PR, now I understand how to make these changes in the future. Will open PRs as I continue to integrate dep-check in our dev flows.

**Comment by tido64** [comment]
> Will open PRs as I continue to integrate dep-check in our dev flows.

Thanks, that's much appreciated. Let us know how it goes 😄
